
package services.profile;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EditProfileImplService", targetNamespace = "http://profile.services/", wsdlLocation = "http://localhost:8083/services/profile/editprofile?wsdl")
public class EditProfileImplService
    extends Service
{

    private final static URL EDITPROFILEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EDITPROFILEIMPLSERVICE_EXCEPTION;
    private final static QName EDITPROFILEIMPLSERVICE_QNAME = new QName("http://profile.services/", "EditProfileImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/services/profile/editprofile?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EDITPROFILEIMPLSERVICE_WSDL_LOCATION = url;
        EDITPROFILEIMPLSERVICE_EXCEPTION = e;
    }

    public EditProfileImplService() {
        super(__getWsdlLocation(), EDITPROFILEIMPLSERVICE_QNAME);
    }

    public EditProfileImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EDITPROFILEIMPLSERVICE_QNAME, features);
    }

    public EditProfileImplService(URL wsdlLocation) {
        super(wsdlLocation, EDITPROFILEIMPLSERVICE_QNAME);
    }

    public EditProfileImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EDITPROFILEIMPLSERVICE_QNAME, features);
    }

    public EditProfileImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EditProfileImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EditProfile
     */
    @WebEndpoint(name = "EditProfileImplPort")
    public EditProfile getEditProfileImplPort() {
        return super.getPort(new QName("http://profile.services/", "EditProfileImplPort"), EditProfile.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EditProfile
     */
    @WebEndpoint(name = "EditProfileImplPort")
    public EditProfile getEditProfileImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://profile.services/", "EditProfileImplPort"), EditProfile.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EDITPROFILEIMPLSERVICE_EXCEPTION!= null) {
            throw EDITPROFILEIMPLSERVICE_EXCEPTION;
        }
        return EDITPROFILEIMPLSERVICE_WSDL_LOCATION;
    }

}
