
package services.order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FinishOrderImplService", targetNamespace = "http://order.services/", wsdlLocation = "http://localhost:8083/services/finishorder?wsdl")
public class FinishOrderImplService
    extends Service
{

    private final static URL FINISHORDERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FINISHORDERIMPLSERVICE_EXCEPTION;
    private final static QName FINISHORDERIMPLSERVICE_QNAME = new QName("http://order.services/", "FinishOrderImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/services/finishorder?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FINISHORDERIMPLSERVICE_WSDL_LOCATION = url;
        FINISHORDERIMPLSERVICE_EXCEPTION = e;
    }

    public FinishOrderImplService() {
        super(__getWsdlLocation(), FINISHORDERIMPLSERVICE_QNAME);
    }

    public FinishOrderImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FINISHORDERIMPLSERVICE_QNAME, features);
    }

    public FinishOrderImplService(URL wsdlLocation) {
        super(wsdlLocation, FINISHORDERIMPLSERVICE_QNAME);
    }

    public FinishOrderImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FINISHORDERIMPLSERVICE_QNAME, features);
    }

    public FinishOrderImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinishOrderImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FinishOrder
     */
    @WebEndpoint(name = "FinishOrderImplPort")
    public FinishOrder getFinishOrderImplPort() {
        return super.getPort(new QName("http://order.services/", "FinishOrderImplPort"), FinishOrder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FinishOrder
     */
    @WebEndpoint(name = "FinishOrderImplPort")
    public FinishOrder getFinishOrderImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://order.services/", "FinishOrderImplPort"), FinishOrder.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FINISHORDERIMPLSERVICE_EXCEPTION!= null) {
            throw FINISHORDERIMPLSERVICE_EXCEPTION;
        }
        return FINISHORDERIMPLSERVICE_WSDL_LOCATION;
    }

}
