
package services.order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Order2ImplService", targetNamespace = "http://order.services/", wsdlLocation = "http://localhost:8083/services/order2?wsdl")
public class Order2ImplService
    extends Service
{

    private final static URL ORDER2IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDER2IMPLSERVICE_EXCEPTION;
    private final static QName ORDER2IMPLSERVICE_QNAME = new QName("http://order.services/", "Order2ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/services/order2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDER2IMPLSERVICE_WSDL_LOCATION = url;
        ORDER2IMPLSERVICE_EXCEPTION = e;
    }

    public Order2ImplService() {
        super(__getWsdlLocation(), ORDER2IMPLSERVICE_QNAME);
    }

    public Order2ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDER2IMPLSERVICE_QNAME, features);
    }

    public Order2ImplService(URL wsdlLocation) {
        super(wsdlLocation, ORDER2IMPLSERVICE_QNAME);
    }

    public Order2ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDER2IMPLSERVICE_QNAME, features);
    }

    public Order2ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Order2ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Order2
     */
    @WebEndpoint(name = "Order2ImplPort")
    public Order2 getOrder2ImplPort() {
        return super.getPort(new QName("http://order.services/", "Order2ImplPort"), Order2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Order2
     */
    @WebEndpoint(name = "Order2ImplPort")
    public Order2 getOrder2ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://order.services/", "Order2ImplPort"), Order2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDER2IMPLSERVICE_EXCEPTION!= null) {
            throw ORDER2IMPLSERVICE_EXCEPTION;
        }
        return ORDER2IMPLSERVICE_WSDL_LOCATION;
    }

}
