
package services.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Order3", targetNamespace = "http://order.services/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Order3 {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getDriverData_Service")
    @WebResult(partName = "return")
    @Action(input = "http://order.services/Order3/getDriverData_ServiceRequest", output = "http://order.services/Order3/getDriverData_ServiceResponse")
    public String getDriverDataService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getDriverData_Account")
    @WebResult(partName = "return")
    @Action(input = "http://order.services/Order3/getDriverData_AccountRequest", output = "http://order.services/Order3/getDriverData_AccountResponse")
    public String getDriverDataAccount(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

}
