
package services.register;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegisterUserImplService", targetNamespace = "http://register.services/", wsdlLocation = "http://localhost:8083/services/register/registeruser?wsdl")
public class RegisterUserImplService
    extends Service
{

    private final static URL REGISTERUSERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTERUSERIMPLSERVICE_EXCEPTION;
    private final static QName REGISTERUSERIMPLSERVICE_QNAME = new QName("http://register.services/", "RegisterUserImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/services/register/registeruser?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTERUSERIMPLSERVICE_WSDL_LOCATION = url;
        REGISTERUSERIMPLSERVICE_EXCEPTION = e;
    }

    public RegisterUserImplService() {
        super(__getWsdlLocation(), REGISTERUSERIMPLSERVICE_QNAME);
    }

    public RegisterUserImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTERUSERIMPLSERVICE_QNAME, features);
    }

    public RegisterUserImplService(URL wsdlLocation) {
        super(wsdlLocation, REGISTERUSERIMPLSERVICE_QNAME);
    }

    public RegisterUserImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTERUSERIMPLSERVICE_QNAME, features);
    }

    public RegisterUserImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegisterUserImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegisterUser
     */
    @WebEndpoint(name = "RegisterUserImplPort")
    public RegisterUser getRegisterUserImplPort() {
        return super.getPort(new QName("http://register.services/", "RegisterUserImplPort"), RegisterUser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegisterUser
     */
    @WebEndpoint(name = "RegisterUserImplPort")
    public RegisterUser getRegisterUserImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://register.services/", "RegisterUserImplPort"), RegisterUser.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTERUSERIMPLSERVICE_EXCEPTION!= null) {
            throw REGISTERUSERIMPLSERVICE_EXCEPTION;
        }
        return REGISTERUSERIMPLSERVICE_WSDL_LOCATION;
    }

}
