
package services.validator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TokenValidatorImplService", targetNamespace = "http://validator.services/", wsdlLocation = "http://localhost:8083/services/validatetoken?wsdl")
public class TokenValidatorImplService
    extends Service
{

    private final static URL TOKENVALIDATORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOKENVALIDATORIMPLSERVICE_EXCEPTION;
    private final static QName TOKENVALIDATORIMPLSERVICE_QNAME = new QName("http://validator.services/", "TokenValidatorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/services/validatetoken?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOKENVALIDATORIMPLSERVICE_WSDL_LOCATION = url;
        TOKENVALIDATORIMPLSERVICE_EXCEPTION = e;
    }

    public TokenValidatorImplService() {
        super(__getWsdlLocation(), TOKENVALIDATORIMPLSERVICE_QNAME);
    }

    public TokenValidatorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOKENVALIDATORIMPLSERVICE_QNAME, features);
    }

    public TokenValidatorImplService(URL wsdlLocation) {
        super(wsdlLocation, TOKENVALIDATORIMPLSERVICE_QNAME);
    }

    public TokenValidatorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOKENVALIDATORIMPLSERVICE_QNAME, features);
    }

    public TokenValidatorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TokenValidatorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TokenValidator
     */
    @WebEndpoint(name = "TokenValidatorImplPort")
    public TokenValidator getTokenValidatorImplPort() {
        return super.getPort(new QName("http://validator.services/", "TokenValidatorImplPort"), TokenValidator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TokenValidator
     */
    @WebEndpoint(name = "TokenValidatorImplPort")
    public TokenValidator getTokenValidatorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://validator.services/", "TokenValidatorImplPort"), TokenValidator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOKENVALIDATORIMPLSERVICE_EXCEPTION!= null) {
            throw TOKENVALIDATORIMPLSERVICE_EXCEPTION;
        }
        return TOKENVALIDATORIMPLSERVICE_WSDL_LOCATION;
    }

}
