
package services.history;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HistoryImplService", targetNamespace = "http://history.services/", wsdlLocation = "http://localhost:8083/services/gethistory?wsdl")
public class HistoryImplService
    extends Service
{

    private final static URL HISTORYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HISTORYIMPLSERVICE_EXCEPTION;
    private final static QName HISTORYIMPLSERVICE_QNAME = new QName("http://history.services/", "HistoryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/services/gethistory?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HISTORYIMPLSERVICE_WSDL_LOCATION = url;
        HISTORYIMPLSERVICE_EXCEPTION = e;
    }

    public HistoryImplService() {
        super(__getWsdlLocation(), HISTORYIMPLSERVICE_QNAME);
    }

    public HistoryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HISTORYIMPLSERVICE_QNAME, features);
    }

    public HistoryImplService(URL wsdlLocation) {
        super(wsdlLocation, HISTORYIMPLSERVICE_QNAME);
    }

    public HistoryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HISTORYIMPLSERVICE_QNAME, features);
    }

    public HistoryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HistoryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns History
     */
    @WebEndpoint(name = "HistoryImplPort")
    public History getHistoryImplPort() {
        return super.getPort(new QName("http://history.services/", "HistoryImplPort"), History.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns History
     */
    @WebEndpoint(name = "HistoryImplPort")
    public History getHistoryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://history.services/", "HistoryImplPort"), History.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HISTORYIMPLSERVICE_EXCEPTION!= null) {
            throw HISTORYIMPLSERVICE_EXCEPTION;
        }
        return HISTORYIMPLSERVICE_WSDL_LOCATION;
    }

}
