
package services.location;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LocationImplService", targetNamespace = "http://location.services/", wsdlLocation = "http://localhost:8083/services/location/editlocation?wsdl")
public class LocationImplService
    extends Service
{

    private final static URL LOCATIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCATIONIMPLSERVICE_EXCEPTION;
    private final static QName LOCATIONIMPLSERVICE_QNAME = new QName("http://location.services/", "LocationImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/services/location/editlocation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCATIONIMPLSERVICE_WSDL_LOCATION = url;
        LOCATIONIMPLSERVICE_EXCEPTION = e;
    }

    public LocationImplService() {
        super(__getWsdlLocation(), LOCATIONIMPLSERVICE_QNAME);
    }

    public LocationImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCATIONIMPLSERVICE_QNAME, features);
    }

    public LocationImplService(URL wsdlLocation) {
        super(wsdlLocation, LOCATIONIMPLSERVICE_QNAME);
    }

    public LocationImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCATIONIMPLSERVICE_QNAME, features);
    }

    public LocationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocationImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Location
     */
    @WebEndpoint(name = "LocationImplPort")
    public Location getLocationImplPort() {
        return super.getPort(new QName("http://location.services/", "LocationImplPort"), Location.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Location
     */
    @WebEndpoint(name = "LocationImplPort")
    public Location getLocationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://location.services/", "LocationImplPort"), Location.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCATIONIMPLSERVICE_EXCEPTION!= null) {
            throw LOCATIONIMPLSERVICE_EXCEPTION;
        }
        return LOCATIONIMPLSERVICE_WSDL_LOCATION;
    }

}
